Update POI-BUILD-PUSH.yml

diff --git a/.github/workflows/POI-BUILD-PUSH.yml b/.github/workflows/POI-BUILD-PUSH.yml
--- a/.github/workflows/POI-BUILD-PUSH.yml
+++ b/.github/workflows/POI-BUILD-PUSH.yml
@@ -44,28 +44,28 @@ jobs:
     - name: Log ACR
       run: |
         az acr login --name ${{ env.ACRNAME }}
-        
-    - name: Push to ACR
-      run: |
-        docker push ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME_POI }}:${{ env.BASEIMAGETAG_POI }}
+       
+ #   - name: Push to ACR
+ #     run: |
+ #       docker push ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME_POI }}:${{ env.BASEIMAGETAG_POI }}
 
-    - name: Start the stage
-      run: |
-        az webapp start -g openhackck258x60rg -n ${{ env.AZURE_WEBAPP_NAME }} --slot staging
+ #   - name: Start the stage
+ #     run: |
+ #       az webapp start -g openhackck258x60rg -n ${{ env.AZURE_WEBAPP_NAME }} --slot staging
     
-    - name: 'Deploy to Azure Web App for Container'
-      uses: azure/webapps-deploy@v2
-      with: 
-        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
-        images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME_POI }}:${{ env.BASEIMAGETAG_POI }}
-        slot-name: staging
+ #   - name: 'Deploy to Azure Web App for Container'
+ #     uses: azure/webapps-deploy@v2
+ #     with: 
+ #       app-name: ${{ env.AZURE_WEBAPP_NAME }} 
+ #       images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME_POI }}:${{ env.BASEIMAGETAG_POI }}
+ #       slot-name: staging
         
     - name: 'Swap'
       run: |
         sleep 15s
-        testStage=`curl -sb -i https://openhackck258x60poi-staging.azurewebsites.netx/api/healthcheck/poi | grep -q Healthy && echo "success" || false`
+        testStage=`curl -sb -i https://openhackck258x60poi-staging.azurewebsites.netx/api/healthcheck/poi | grep -q Healthy && echo "success" || echo 'failed'`
         [ $testStage != 'success' ] && az webapp deployment slot swap -g openhackck258x60rg -n ${{ env.AZURE_WEBAPP_NAME }} --slot staging --target-slot production
-        testProd=`curl -sb -i https://openhackck258x60poi.azurewebsites.net/api/healthcheck/poi | grep -q Healthy && echo "success" || false`
+        testProd=`curl -sb -i https://openhackck258x60poi.azurewebsites.net/api/healthcheck/poi | grep -q Healthy && echo "success" || echo 'failed'`
         [ $testProd != 'success' ] && az webapp deployment slot swap -g openhackck258x60rg -n ${{ env.AZURE_WEBAPP_NAME }} --slot production --target-slot staging || echo "Successful"
     
         
