Update USER-JAVA-BUILD-PUSH.yml

diff --git a/.github/workflows/USER-JAVA-BUILD-PUSH.yml b/.github/workflows/USER-JAVA-BUILD-PUSH.yml
--- a/.github/workflows/USER-JAVA-BUILD-PUSH.yml
+++ b/.github/workflows/USER-JAVA-BUILD-PUSH.yml
@@ -56,10 +56,14 @@ jobs:
     - name: 'Swap'
       run: |
         sleep 15s
-        curl -sb -i https://openhackck258x60poi-staging.azurewebsites.net/api/healthcheck/poi | grep -q Healthy && echo "success" || false
-        az webapp deployment slot swap -g openhackck258x60rg -n ${{ env.AZURE_WEBAPP_NAME }} --slot staging --target-slot production
-        test=`curl -sb -i https://openhackck258x60poi.azurewebsites.net/api/healthcheck/poi | grep -q Healthy && echo "success" || false`
-        [ $test != 'success' ] && az webapp deployment slot swap -g openhackck258x60rg -n ${{ env.AZURE_WEBAPP_NAME }} --slot production --target-slot staging || false
+        testStage=`curl -sb -i https://openhackck258x60poi-staging.azurewebsites.net/api/healthcheck/poi | grep -q Healthy && echo "success" || echo 'failed'`
+        echo 'testStage' $testStage
+        [ $testStage == 'success' ] && az webapp deployment slot swap -g openhackck258x60rg -n ${{ env.AZURE_WEBAPP_NAME }} --slot staging --target-slot production
+        testProd=`curl -sb -i https://openhackck258x60poi.azurewebsites.netx/api/healthcheck/poi | grep -q Healthy && echo "success" || echo 'failed'`
+        echo 'testProd' $testProd
+        [ $testProd != 'success' ] && az webapp deployment slot swap -g openhackck258x60rg -n ${{ env.AZURE_WEBAPP_NAME }} --slot production --target-slot staging || echo "Successful"
+    
         
-        
-       
+    - name: Stop the stage
+      run: |
+        az webapp stop -g openhackck258x60rg -n ${{ env.AZURE_WEBAPP_NAME }} --slot staging
